services:
  - type: web
    name: edutube-backend
    env: python
    region: singapore
    plan: free
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: python deploy.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.7
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        value: "postgresql://edutube_db_user:d4QuV99nvpcVQYPmRJOzjUrGWjIBuJKc@dpg-cvrds7ggjchc73b77280-a.oregon-postgres.render.com/edutube_db"
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "https://edutube-rust.vercel.app,http://localhost:3000"
      - key: YOUTUBE_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: THIRDWEB_API_KEY
        sync: false
      - key: THIRDWEB_PRIVATE_KEY
        sync: false
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_API_KEY
        sync: false
      - key: SITE_URL
        value: "https://edutube-backend.onrender.com"
      - key: SIMULATE_MINTING
        value: "True"
      - key: REDIS_URL
        sync: false
      - key: BLOCKCHAIN_NETWORK
        value: "polygon-mumbai"
      - key: BLOCKCHAIN_RPC_URL
        value: "https://rpc-mumbai.maticvigil.com"
