# Generated by Django 5.1.7 on 2025-03-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['id']},
        ),
    ]
